comment: false
codecov:
  notify:
    after_n_builds: 4 # must match number of pytest-split shards in .github/workflows/test.yml
coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 5%
    project:
      default:
        target: auto
        threshold: 2%
