name: GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: janosh/workflows/.github/workflows/nodejs-gh-pages.yml@main
    with:
      install-cmd: npm install --force
      python-version: '3.11'
      working-directory: site
      pre-build: |
        pip install -e '..[gh-pages]'
        python ../site/make_docs.py
