name: Upload widgets assets on GitHub release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Version to upload assets for (e.g. v0.16.0)
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Build web files
        run: |
          cd pymatviz/widgets
          deno task build

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Upload assets to release
        run: |
          gh release upload ${{ steps.get_version.outputs.version }} \
            pymatviz/widgets/web/build/matterviz.mjs \
            pymatviz/widgets/web/build/matterviz.css \
            --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
